### PR TITLE
API call for course & post pages

### PR DESCRIPTION
**Pull request by uier**

### CODE REVIEW

**Review by DWyatb — COMMENTED** [review]
I'm wondering if the frontend definition of type is same with backend now. Most types now use in frontend are imported by type.ts and api.ts, but I remember Jacob said that the type of backend has been updated, so we need to update by using uni.ts or prisma. I will update FullScreenCard.vue in this iteration. Others file, like /course/index.vue, it import like as follows: 
```ts
import type { CourseInfo, CourseListFilter, CourseMeta, CourseTypeListFilter } from "../../types";
import { courses } from "../../api";)
```
I'm not sure if the type will conflict now.
@JacobLinCool

**Comment by JacobLinCool** [comment]
> I'm not sure if the type will conflict now.

You are correct. The type definitions should all be imported from package `unicourse` / `@unicourse-tw/prisma`. The legacy ones (`types.ts`, `api.ts`) are only used to make the type check pass in ci. They should be removed once the old components were refactored.

**Comment by DWyatb** [comment]
I want to know if unicourse / @unicourse-tw/prisma have types to match the types as follows
```ts
import type { CourseInfo, CourseListFilter, CourseMeta, CourseTypeListFilter } from "../../types";
import { courses } from "../../api";)
```
@JacobLinCool 

Since the deadline is limited to 12/25, is there anything I can celp? @uier

**Comment by JacobLinCool** [comment]
> I want to know if unicourse / @unicourse-tw/prisma have types to match the types as follows

No. I think most of them (except `courses`, the corresponding new type should be `Course` from `@unicourse-tw/prisma`) are not necessary. Can you give me some use case that the current solution doesn't work?

**Comment by uier** [comment]
@DWyatb 有些東西我再改一下，好了會 re-request for your review

**Review by DWyatb — APPROVED** [review]

**Pull request merged**
